version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/requirements/base/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/requirements/local/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/requirements/production/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "pip"
    directory: "/requirements/testing/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/deploy/production/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/deploy/dev/"
    schedule:
      interval: "monthly"