# This file create a "studentenportal" image for the production deployment
#  of the studentenportal.
# Images have the same versioning as the studentenportal itself,
#  and is uploaded to dockerhub.
FROM studentenportal-base

#TODO
