# This file create a "studentenportal" image for the dev environment.
# Additional packages for dev are added here.
FROM studentenportal/studentenportal-base

ADD requirements/local.txt /tmp/requirements/local.txt
RUN pip install -r /tmp/requirements/local.txt
RUN apt-get install postgresql-client
RUN gem install --no-rdoc --no-ri sass -v 3.4.2
WORKDIR /srv/www/studentenportal
USER studentenportal
CMD ["./start-dev.sh"]
