# Generated by Django 2.2.9 on 2020-01-22 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0002_auto_20161124_2111"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="documentdownload",
            index_together={("document", "timestamp")},
        ),
        migrations.RemoveField(
            model_name="documentdownload",
            name="ip",
        ),
    ]
