# Generated by Django 2.2.11 on 2020-03-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20200122_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='flattr_disabled',
        ),
    ]
