# Generated by Django 2.2.17 on 2020-12-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_auto_20201130_1003"),
        ("documents", "0005_auto_20201130_1115"),
    ]

    operations = []
