# Generated by Django 5.0 on 2026-09-12 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TippComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Kommentar')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipp_comments', to=settings.AUTH_USER_MODEL)),
                ('tipp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tipps.tipp')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
