# Generated by Django 2.2.9 on 2020-01-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0004_auto_20200121_1625"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="twitter",
        ),
    ]
