# Generated by Django 5.2.16 on 2026-10-02 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("front", "0009_lowercase_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Optionale zweite Adresse, an die Benachrichtigungen zusätzlich gesendet werden.",
                max_length=254,
                verbose_name="Zusätzliche E-Mail-Adresse",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="receive_event_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Ob du eine E-Mail erhalten möchtest, wenn ein neues Event erfasst wird.",
                verbose_name="Neue Events per E-Mail",
            ),
        ),
        migrations.CreateModel(
            name="InactivityNotice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inactivity_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
